apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-11-demo-deployment
  namespace: gradleproject
  labels:
    app: java-11-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-11-demo
  template:
    metadata:
      labels:
        app: java-11-demo
    spec:
      containers:
      - name: java-11-demo
        image: localhost:5000/java11demo
        ports:
        - containerPort: 8081
