apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-11-demo-deployment
  namespace: gradleproject
  labels:
    app: java-11-demo-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        apps: java-11-demo
    spec:
      containers:
      - name: java-11-demo
        image: frozenmind/jobsearch:java11demolatest
        ports:
        - containerPort: 8081
